# Generated by Django 2.2 on 2021-04-09 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_models_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['-likes']},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['dated']},
        ),
    ]
