# Generated by Django 2.2.4 on 2021-04-11 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_changed_DateField_default'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'default_manager_name': 'objects', 'ordering': ['dated']},
        ),
    ]
