# Generated by Django 2.2.4 on 2021-04-29 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_models_created'),
        ('questions', '0009_auto_20210425_1720'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={},
        ),
        migrations.RemoveField(
            model_name='answer',
            name='likes',
        ),
        migrations.CreateModel(
            name='AnswerVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.CharField(max_length=7)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserAccount')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='questions.Answer')),
            ],
        ),
    ]
