# Generated by Django 2.2.4 on 2021-05-09 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0010_auto_20210428_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='vote_tally',
            field=models.IntegerField(default=0),
        ),
    ]
