# Generated by Django 2.2.4 on 2021-05-10 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0011_Add_votetally_field_for_Question'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='vote_tally',
            field=models.IntegerField(default=0),
        ),
    ]
